create table "public"."CAMP_CLASSES" (
    "class_id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "class_num" integer not null,
    "created_at" timestamp with time zone default now()
);


create table "public"."MEMORIES" (
    "memory_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "name" character varying(255),
    "image_uri" text,
    "created_at" timestamp with time zone default now()
);


create table "public"."POLLS" (
    "poll_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "made_by" bigint not null,
    "poll_name" character varying(255) not null,
    "created_at" timestamp with time zone default now(),
    "deadline" timestamp with time zone
);


create table "public"."POLL_OPTIONS" (
    "option_id" bigint generated by default as identity not null,
    "poll_id" bigint not null,
    "option_name" character varying(255) not null
);


create table "public"."PROJECTS" (
    "project_id" bigint generated by default as identity not null,
    "project_name" character varying(100) not null,
    "class_id" bigint not null,
    "week_num" integer,
    "user_id_1" bigint not null,
    "user_id_2" bigint not null,
    "created_at" timestamp with time zone default now(),
    "planning" text,
    "progress" integer default 0
);


create table "public"."SCHEDULES" (
    "schedule_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "related_poll" bigint,
    "schedule_name" character varying(255) not null,
    "description" text,
    "when" timestamp with time zone not null,
    "created_at" timestamp with time zone default now()
);


create table "public"."SCHEDULE_USERS" (
    "schedule_id" bigint not null,
    "user_id" bigint not null,
    "role" character varying(50),
    "status" character varying(20)
);


create table "public"."SCRUMS" (
    "scrum_id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "date" date not null,
    "done" text,
    "plan" text,
    "others" text
);


create table "public"."SEASONS" (
    "season_id" bigint generated by default as identity not null,
    "name" character varying(100) not null
);


create table "public"."TOPICS" (
    "topic_id" bigint generated by default as identity not null,
    "creator_id" bigint not null,
    "title" character varying(255) not null,
    "description" text,
    "created_at" timestamp with time zone default now()
);


create table "public"."TOPIC_INTERESTS" (
    "user_id" bigint not null,
    "topic_id" bigint not null,
    "level" integer,
    "expressed_at" timestamp with time zone default now()
);


create table "public"."USERS" (
    "user_id" bigint generated by default as identity not null,
    "class_id" bigint,
    "name" character varying(50) not null,
    "email" character varying(100) not null,
    "password" character varying(255) not null,
    "created_at" timestamp with time zone default now()
);


create table "public"."VOTES" (
    "vote_id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "poll_id" bigint not null,
    "option_id" bigint not null,
    "voted_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX "CAMP_CLASSES_pkey" ON public."CAMP_CLASSES" USING btree (class_id);

CREATE UNIQUE INDEX "MEMORIES_pkey" ON public."MEMORIES" USING btree (memory_id);

CREATE UNIQUE INDEX "POLLS_pkey" ON public."POLLS" USING btree (poll_id);

CREATE UNIQUE INDEX "POLL_OPTIONS_pkey" ON public."POLL_OPTIONS" USING btree (option_id);

CREATE UNIQUE INDEX "PROJECTS_pkey" ON public."PROJECTS" USING btree (project_id);

CREATE UNIQUE INDEX "SCHEDULES_pkey" ON public."SCHEDULES" USING btree (schedule_id);

CREATE UNIQUE INDEX "SCHEDULE_USERS_pkey" ON public."SCHEDULE_USERS" USING btree (schedule_id, user_id);

CREATE UNIQUE INDEX "SCRUMS_pkey" ON public."SCRUMS" USING btree (scrum_id);

CREATE UNIQUE INDEX "SEASONS_pkey" ON public."SEASONS" USING btree (season_id);

CREATE UNIQUE INDEX "TOPICS_pkey" ON public."TOPICS" USING btree (topic_id);

CREATE UNIQUE INDEX "TOPIC_INTERESTS_pkey" ON public."TOPIC_INTERESTS" USING btree (user_id, topic_id);

CREATE UNIQUE INDEX "USERS_email_key" ON public."USERS" USING btree (email);

CREATE UNIQUE INDEX "USERS_pkey" ON public."USERS" USING btree (user_id);

CREATE UNIQUE INDEX "VOTES_pkey" ON public."VOTES" USING btree (vote_id);

CREATE UNIQUE INDEX "VOTES_user_id_poll_id_key" ON public."VOTES" USING btree (user_id, poll_id);

alter table "public"."CAMP_CLASSES" add constraint "CAMP_CLASSES_pkey" PRIMARY KEY using index "CAMP_CLASSES_pkey";

alter table "public"."MEMORIES" add constraint "MEMORIES_pkey" PRIMARY KEY using index "MEMORIES_pkey";

alter table "public"."POLLS" add constraint "POLLS_pkey" PRIMARY KEY using index "POLLS_pkey";

alter table "public"."POLL_OPTIONS" add constraint "POLL_OPTIONS_pkey" PRIMARY KEY using index "POLL_OPTIONS_pkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_pkey" PRIMARY KEY using index "PROJECTS_pkey";

alter table "public"."SCHEDULES" add constraint "SCHEDULES_pkey" PRIMARY KEY using index "SCHEDULES_pkey";

alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_pkey" PRIMARY KEY using index "SCHEDULE_USERS_pkey";

alter table "public"."SCRUMS" add constraint "SCRUMS_pkey" PRIMARY KEY using index "SCRUMS_pkey";

alter table "public"."SEASONS" add constraint "SEASONS_pkey" PRIMARY KEY using index "SEASONS_pkey";

alter table "public"."TOPICS" add constraint "TOPICS_pkey" PRIMARY KEY using index "TOPICS_pkey";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_pkey" PRIMARY KEY using index "TOPIC_INTERESTS_pkey";

alter table "public"."USERS" add constraint "USERS_pkey" PRIMARY KEY using index "USERS_pkey";

alter table "public"."VOTES" add constraint "VOTES_pkey" PRIMARY KEY using index "VOTES_pkey";

alter table "public"."CAMP_CLASSES" add constraint "CAMP_CLASSES_season_id_fkey" FOREIGN KEY (season_id) REFERENCES "SEASONS"(season_id) not valid;

alter table "public"."CAMP_CLASSES" validate constraint "CAMP_CLASSES_season_id_fkey";

alter table "public"."MEMORIES" add constraint "MEMORIES_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;

alter table "public"."MEMORIES" validate constraint "MEMORIES_class_id_fkey";

alter table "public"."POLLS" add constraint "POLLS_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;

alter table "public"."POLLS" validate constraint "POLLS_class_id_fkey";

alter table "public"."POLLS" add constraint "POLLS_made_by_fkey" FOREIGN KEY (made_by) REFERENCES "USERS"(user_id) not valid;

alter table "public"."POLLS" validate constraint "POLLS_made_by_fkey";

alter table "public"."POLL_OPTIONS" add constraint "POLL_OPTIONS_poll_id_fkey" FOREIGN KEY (poll_id) REFERENCES "POLLS"(poll_id) ON DELETE CASCADE not valid;

alter table "public"."POLL_OPTIONS" validate constraint "POLL_OPTIONS_poll_id_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_check" CHECK ((user_id_1 < user_id_2)) not valid;

alter table "public"."PROJECTS" validate constraint "PROJECTS_check";

alter table "public"."PROJECTS" add constraint "PROJECTS_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;

alter table "public"."PROJECTS" validate constraint "PROJECTS_class_id_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_user_id_1_fkey" FOREIGN KEY (user_id_1) REFERENCES "USERS"(user_id) not valid;

alter table "public"."PROJECTS" validate constraint "PROJECTS_user_id_1_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_user_id_2_fkey" FOREIGN KEY (user_id_2) REFERENCES "USERS"(user_id) not valid;

alter table "public"."PROJECTS" validate constraint "PROJECTS_user_id_2_fkey";

alter table "public"."SCHEDULES" add constraint "SCHEDULES_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;

alter table "public"."SCHEDULES" validate constraint "SCHEDULES_class_id_fkey";

alter table "public"."SCHEDULES" add constraint "SCHEDULES_related_poll_fkey" FOREIGN KEY (related_poll) REFERENCES "POLLS"(poll_id) ON DELETE SET NULL not valid;

alter table "public"."SCHEDULES" validate constraint "SCHEDULES_related_poll_fkey";

alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_schedule_id_fkey" FOREIGN KEY (schedule_id) REFERENCES "SCHEDULES"(schedule_id) ON DELETE CASCADE not valid;

alter table "public"."SCHEDULE_USERS" validate constraint "SCHEDULE_USERS_schedule_id_fkey";

alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "USERS"(user_id) ON DELETE CASCADE not valid;

alter table "public"."SCHEDULE_USERS" validate constraint "SCHEDULE_USERS_user_id_fkey";

alter table "public"."SCRUMS" add constraint "SCRUMS_project_id_fkey" FOREIGN KEY (project_id) REFERENCES "PROJECTS"(project_id) ON DELETE CASCADE not valid;

alter table "public"."SCRUMS" validate constraint "SCRUMS_project_id_fkey";

alter table "public"."TOPICS" add constraint "TOPICS_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES "USERS"(user_id) not valid;

alter table "public"."TOPICS" validate constraint "TOPICS_creator_id_fkey";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_level_check" CHECK (((level >= 1) AND (level <= 5))) not valid;

alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_level_check";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES "TOPICS"(topic_id) ON DELETE CASCADE not valid;

alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_topic_id_fkey";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "USERS"(user_id) ON DELETE CASCADE not valid;

alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_user_id_fkey";

alter table "public"."USERS" add constraint "USERS_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;

alter table "public"."USERS" validate constraint "USERS_class_id_fkey";

alter table "public"."USERS" add constraint "USERS_email_key" UNIQUE using index "USERS_email_key";

alter table "public"."VOTES" add constraint "VOTES_option_id_fkey" FOREIGN KEY (option_id) REFERENCES "POLL_OPTIONS"(option_id) ON DELETE CASCADE not valid;

alter table "public"."VOTES" validate constraint "VOTES_option_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_poll_id_fkey" FOREIGN KEY (poll_id) REFERENCES "POLLS"(poll_id) ON DELETE CASCADE not valid;

alter table "public"."VOTES" validate constraint "VOTES_poll_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "USERS"(user_id) ON DELETE CASCADE not valid;

alter table "public"."VOTES" validate constraint "VOTES_user_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_user_id_poll_id_key" UNIQUE using index "VOTES_user_id_poll_id_key";

grant delete on table "public"."CAMP_CLASSES" to "anon";

grant insert on table "public"."CAMP_CLASSES" to "anon";

grant references on table "public"."CAMP_CLASSES" to "anon";

grant select on table "public"."CAMP_CLASSES" to "anon";

grant trigger on table "public"."CAMP_CLASSES" to "anon";

grant truncate on table "public"."CAMP_CLASSES" to "anon";

grant update on table "public"."CAMP_CLASSES" to "anon";

grant delete on table "public"."CAMP_CLASSES" to "authenticated";

grant insert on table "public"."CAMP_CLASSES" to "authenticated";

grant references on table "public"."CAMP_CLASSES" to "authenticated";

grant select on table "public"."CAMP_CLASSES" to "authenticated";

grant trigger on table "public"."CAMP_CLASSES" to "authenticated";

grant truncate on table "public"."CAMP_CLASSES" to "authenticated";

grant update on table "public"."CAMP_CLASSES" to "authenticated";

grant delete on table "public"."CAMP_CLASSES" to "service_role";

grant insert on table "public"."CAMP_CLASSES" to "service_role";

grant references on table "public"."CAMP_CLASSES" to "service_role";

grant select on table "public"."CAMP_CLASSES" to "service_role";

grant trigger on table "public"."CAMP_CLASSES" to "service_role";

grant truncate on table "public"."CAMP_CLASSES" to "service_role";

grant update on table "public"."CAMP_CLASSES" to "service_role";

grant delete on table "public"."MEMORIES" to "anon";

grant insert on table "public"."MEMORIES" to "anon";

grant references on table "public"."MEMORIES" to "anon";

grant select on table "public"."MEMORIES" to "anon";

grant trigger on table "public"."MEMORIES" to "anon";

grant truncate on table "public"."MEMORIES" to "anon";

grant update on table "public"."MEMORIES" to "anon";

grant delete on table "public"."MEMORIES" to "authenticated";

grant insert on table "public"."MEMORIES" to "authenticated";

grant references on table "public"."MEMORIES" to "authenticated";

grant select on table "public"."MEMORIES" to "authenticated";

grant trigger on table "public"."MEMORIES" to "authenticated";

grant truncate on table "public"."MEMORIES" to "authenticated";

grant update on table "public"."MEMORIES" to "authenticated";

grant delete on table "public"."MEMORIES" to "service_role";

grant insert on table "public"."MEMORIES" to "service_role";

grant references on table "public"."MEMORIES" to "service_role";

grant select on table "public"."MEMORIES" to "service_role";

grant trigger on table "public"."MEMORIES" to "service_role";

grant truncate on table "public"."MEMORIES" to "service_role";

grant update on table "public"."MEMORIES" to "service_role";

grant delete on table "public"."POLLS" to "anon";

grant insert on table "public"."POLLS" to "anon";

grant references on table "public"."POLLS" to "anon";

grant select on table "public"."POLLS" to "anon";

grant trigger on table "public"."POLLS" to "anon";

grant truncate on table "public"."POLLS" to "anon";

grant update on table "public"."POLLS" to "anon";

grant delete on table "public"."POLLS" to "authenticated";

grant insert on table "public"."POLLS" to "authenticated";

grant references on table "public"."POLLS" to "authenticated";

grant select on table "public"."POLLS" to "authenticated";

grant trigger on table "public"."POLLS" to "authenticated";

grant truncate on table "public"."POLLS" to "authenticated";

grant update on table "public"."POLLS" to "authenticated";

grant delete on table "public"."POLLS" to "service_role";

grant insert on table "public"."POLLS" to "service_role";

grant references on table "public"."POLLS" to "service_role";

grant select on table "public"."POLLS" to "service_role";

grant trigger on table "public"."POLLS" to "service_role";

grant truncate on table "public"."POLLS" to "service_role";

grant update on table "public"."POLLS" to "service_role";

grant delete on table "public"."POLL_OPTIONS" to "anon";

grant insert on table "public"."POLL_OPTIONS" to "anon";

grant references on table "public"."POLL_OPTIONS" to "anon";

grant select on table "public"."POLL_OPTIONS" to "anon";

grant trigger on table "public"."POLL_OPTIONS" to "anon";

grant truncate on table "public"."POLL_OPTIONS" to "anon";

grant update on table "public"."POLL_OPTIONS" to "anon";

grant delete on table "public"."POLL_OPTIONS" to "authenticated";

grant insert on table "public"."POLL_OPTIONS" to "authenticated";

grant references on table "public"."POLL_OPTIONS" to "authenticated";

grant select on table "public"."POLL_OPTIONS" to "authenticated";

grant trigger on table "public"."POLL_OPTIONS" to "authenticated";

grant truncate on table "public"."POLL_OPTIONS" to "authenticated";

grant update on table "public"."POLL_OPTIONS" to "authenticated";

grant delete on table "public"."POLL_OPTIONS" to "service_role";

grant insert on table "public"."POLL_OPTIONS" to "service_role";

grant references on table "public"."POLL_OPTIONS" to "service_role";

grant select on table "public"."POLL_OPTIONS" to "service_role";

grant trigger on table "public"."POLL_OPTIONS" to "service_role";

grant truncate on table "public"."POLL_OPTIONS" to "service_role";

grant update on table "public"."POLL_OPTIONS" to "service_role";

grant delete on table "public"."PROJECTS" to "anon";

grant insert on table "public"."PROJECTS" to "anon";

grant references on table "public"."PROJECTS" to "anon";

grant select on table "public"."PROJECTS" to "anon";

grant trigger on table "public"."PROJECTS" to "anon";

grant truncate on table "public"."PROJECTS" to "anon";

grant update on table "public"."PROJECTS" to "anon";

grant delete on table "public"."PROJECTS" to "authenticated";

grant insert on table "public"."PROJECTS" to "authenticated";

grant references on table "public"."PROJECTS" to "authenticated";

grant select on table "public"."PROJECTS" to "authenticated";

grant trigger on table "public"."PROJECTS" to "authenticated";

grant truncate on table "public"."PROJECTS" to "authenticated";

grant update on table "public"."PROJECTS" to "authenticated";

grant delete on table "public"."PROJECTS" to "service_role";

grant insert on table "public"."PROJECTS" to "service_role";

grant references on table "public"."PROJECTS" to "service_role";

grant select on table "public"."PROJECTS" to "service_role";

grant trigger on table "public"."PROJECTS" to "service_role";

grant truncate on table "public"."PROJECTS" to "service_role";

grant update on table "public"."PROJECTS" to "service_role";

grant delete on table "public"."SCHEDULES" to "anon";

grant insert on table "public"."SCHEDULES" to "anon";

grant references on table "public"."SCHEDULES" to "anon";

grant select on table "public"."SCHEDULES" to "anon";

grant trigger on table "public"."SCHEDULES" to "anon";

grant truncate on table "public"."SCHEDULES" to "anon";

grant update on table "public"."SCHEDULES" to "anon";

grant delete on table "public"."SCHEDULES" to "authenticated";

grant insert on table "public"."SCHEDULES" to "authenticated";

grant references on table "public"."SCHEDULES" to "authenticated";

grant select on table "public"."SCHEDULES" to "authenticated";

grant trigger on table "public"."SCHEDULES" to "authenticated";

grant truncate on table "public"."SCHEDULES" to "authenticated";

grant update on table "public"."SCHEDULES" to "authenticated";

grant delete on table "public"."SCHEDULES" to "service_role";

grant insert on table "public"."SCHEDULES" to "service_role";

grant references on table "public"."SCHEDULES" to "service_role";

grant select on table "public"."SCHEDULES" to "service_role";

grant trigger on table "public"."SCHEDULES" to "service_role";

grant truncate on table "public"."SCHEDULES" to "service_role";

grant update on table "public"."SCHEDULES" to "service_role";

grant delete on table "public"."SCHEDULE_USERS" to "anon";

grant insert on table "public"."SCHEDULE_USERS" to "anon";

grant references on table "public"."SCHEDULE_USERS" to "anon";

grant select on table "public"."SCHEDULE_USERS" to "anon";

grant trigger on table "public"."SCHEDULE_USERS" to "anon";

grant truncate on table "public"."SCHEDULE_USERS" to "anon";

grant update on table "public"."SCHEDULE_USERS" to "anon";

grant delete on table "public"."SCHEDULE_USERS" to "authenticated";

grant insert on table "public"."SCHEDULE_USERS" to "authenticated";

grant references on table "public"."SCHEDULE_USERS" to "authenticated";

grant select on table "public"."SCHEDULE_USERS" to "authenticated";

grant trigger on table "public"."SCHEDULE_USERS" to "authenticated";

grant truncate on table "public"."SCHEDULE_USERS" to "authenticated";

grant update on table "public"."SCHEDULE_USERS" to "authenticated";

grant delete on table "public"."SCHEDULE_USERS" to "service_role";

grant insert on table "public"."SCHEDULE_USERS" to "service_role";

grant references on table "public"."SCHEDULE_USERS" to "service_role";

grant select on table "public"."SCHEDULE_USERS" to "service_role";

grant trigger on table "public"."SCHEDULE_USERS" to "service_role";

grant truncate on table "public"."SCHEDULE_USERS" to "service_role";

grant update on table "public"."SCHEDULE_USERS" to "service_role";

grant delete on table "public"."SCRUMS" to "anon";

grant insert on table "public"."SCRUMS" to "anon";

grant references on table "public"."SCRUMS" to "anon";

grant select on table "public"."SCRUMS" to "anon";

grant trigger on table "public"."SCRUMS" to "anon";

grant truncate on table "public"."SCRUMS" to "anon";

grant update on table "public"."SCRUMS" to "anon";

grant delete on table "public"."SCRUMS" to "authenticated";

grant insert on table "public"."SCRUMS" to "authenticated";

grant references on table "public"."SCRUMS" to "authenticated";

grant select on table "public"."SCRUMS" to "authenticated";

grant trigger on table "public"."SCRUMS" to "authenticated";

grant truncate on table "public"."SCRUMS" to "authenticated";

grant update on table "public"."SCRUMS" to "authenticated";

grant delete on table "public"."SCRUMS" to "service_role";

grant insert on table "public"."SCRUMS" to "service_role";

grant references on table "public"."SCRUMS" to "service_role";

grant select on table "public"."SCRUMS" to "service_role";

grant trigger on table "public"."SCRUMS" to "service_role";

grant truncate on table "public"."SCRUMS" to "service_role";

grant update on table "public"."SCRUMS" to "service_role";

grant delete on table "public"."SEASONS" to "anon";

grant insert on table "public"."SEASONS" to "anon";

grant references on table "public"."SEASONS" to "anon";

grant select on table "public"."SEASONS" to "anon";

grant trigger on table "public"."SEASONS" to "anon";

grant truncate on table "public"."SEASONS" to "anon";

grant update on table "public"."SEASONS" to "anon";

grant delete on table "public"."SEASONS" to "authenticated";

grant insert on table "public"."SEASONS" to "authenticated";

grant references on table "public"."SEASONS" to "authenticated";

grant select on table "public"."SEASONS" to "authenticated";

grant trigger on table "public"."SEASONS" to "authenticated";

grant truncate on table "public"."SEASONS" to "authenticated";

grant update on table "public"."SEASONS" to "authenticated";

grant delete on table "public"."SEASONS" to "service_role";

grant insert on table "public"."SEASONS" to "service_role";

grant references on table "public"."SEASONS" to "service_role";

grant select on table "public"."SEASONS" to "service_role";

grant trigger on table "public"."SEASONS" to "service_role";

grant truncate on table "public"."SEASONS" to "service_role";

grant update on table "public"."SEASONS" to "service_role";

grant delete on table "public"."TOPICS" to "anon";

grant insert on table "public"."TOPICS" to "anon";

grant references on table "public"."TOPICS" to "anon";

grant select on table "public"."TOPICS" to "anon";

grant trigger on table "public"."TOPICS" to "anon";

grant truncate on table "public"."TOPICS" to "anon";

grant update on table "public"."TOPICS" to "anon";

grant delete on table "public"."TOPICS" to "authenticated";

grant insert on table "public"."TOPICS" to "authenticated";

grant references on table "public"."TOPICS" to "authenticated";

grant select on table "public"."TOPICS" to "authenticated";

grant trigger on table "public"."TOPICS" to "authenticated";

grant truncate on table "public"."TOPICS" to "authenticated";

grant update on table "public"."TOPICS" to "authenticated";

grant delete on table "public"."TOPICS" to "service_role";

grant insert on table "public"."TOPICS" to "service_role";

grant references on table "public"."TOPICS" to "service_role";

grant select on table "public"."TOPICS" to "service_role";

grant trigger on table "public"."TOPICS" to "service_role";

grant truncate on table "public"."TOPICS" to "service_role";

grant update on table "public"."TOPICS" to "service_role";

grant delete on table "public"."TOPIC_INTERESTS" to "anon";

grant insert on table "public"."TOPIC_INTERESTS" to "anon";

grant references on table "public"."TOPIC_INTERESTS" to "anon";

grant select on table "public"."TOPIC_INTERESTS" to "anon";

grant trigger on table "public"."TOPIC_INTERESTS" to "anon";

grant truncate on table "public"."TOPIC_INTERESTS" to "anon";

grant update on table "public"."TOPIC_INTERESTS" to "anon";

grant delete on table "public"."TOPIC_INTERESTS" to "authenticated";

grant insert on table "public"."TOPIC_INTERESTS" to "authenticated";

grant references on table "public"."TOPIC_INTERESTS" to "authenticated";

grant select on table "public"."TOPIC_INTERESTS" to "authenticated";

grant trigger on table "public"."TOPIC_INTERESTS" to "authenticated";

grant truncate on table "public"."TOPIC_INTERESTS" to "authenticated";

grant update on table "public"."TOPIC_INTERESTS" to "authenticated";

grant delete on table "public"."TOPIC_INTERESTS" to "service_role";

grant insert on table "public"."TOPIC_INTERESTS" to "service_role";

grant references on table "public"."TOPIC_INTERESTS" to "service_role";

grant select on table "public"."TOPIC_INTERESTS" to "service_role";

grant trigger on table "public"."TOPIC_INTERESTS" to "service_role";

grant truncate on table "public"."TOPIC_INTERESTS" to "service_role";

grant update on table "public"."TOPIC_INTERESTS" to "service_role";

grant delete on table "public"."USERS" to "anon";

grant insert on table "public"."USERS" to "anon";

grant references on table "public"."USERS" to "anon";

grant select on table "public"."USERS" to "anon";

grant trigger on table "public"."USERS" to "anon";

grant truncate on table "public"."USERS" to "anon";

grant update on table "public"."USERS" to "anon";

grant delete on table "public"."USERS" to "authenticated";

grant insert on table "public"."USERS" to "authenticated";

grant references on table "public"."USERS" to "authenticated";

grant select on table "public"."USERS" to "authenticated";

grant trigger on table "public"."USERS" to "authenticated";

grant truncate on table "public"."USERS" to "authenticated";

grant update on table "public"."USERS" to "authenticated";

grant delete on table "public"."USERS" to "service_role";

grant insert on table "public"."USERS" to "service_role";

grant references on table "public"."USERS" to "service_role";

grant select on table "public"."USERS" to "service_role";

grant trigger on table "public"."USERS" to "service_role";

grant truncate on table "public"."USERS" to "service_role";

grant update on table "public"."USERS" to "service_role";

grant delete on table "public"."VOTES" to "anon";

grant insert on table "public"."VOTES" to "anon";

grant references on table "public"."VOTES" to "anon";

grant select on table "public"."VOTES" to "anon";

grant trigger on table "public"."VOTES" to "anon";

grant truncate on table "public"."VOTES" to "anon";

grant update on table "public"."VOTES" to "anon";

grant delete on table "public"."VOTES" to "authenticated";

grant insert on table "public"."VOTES" to "authenticated";

grant references on table "public"."VOTES" to "authenticated";

grant select on table "public"."VOTES" to "authenticated";

grant trigger on table "public"."VOTES" to "authenticated";

grant truncate on table "public"."VOTES" to "authenticated";

grant update on table "public"."VOTES" to "authenticated";

grant delete on table "public"."VOTES" to "service_role";

grant insert on table "public"."VOTES" to "service_role";

grant references on table "public"."VOTES" to "service_role";

grant select on table "public"."VOTES" to "service_role";

grant trigger on table "public"."VOTES" to "service_role";

grant truncate on table "public"."VOTES" to "service_role";

grant update on table "public"."VOTES" to "service_role";


