-- Complete database schema with PROFILES table instead of USERS
-- This migration replaces all USER table relations with PROFILE table relations

-- SEASONS table (unchanged)
create table "public"."SEASONS" (
    "season_id" bigint generated by default as identity not null,
    "name" character varying(100) not null
);

-- CAMP_CLASSES table (unchanged)
create table "public"."CAMP_CLASSES" (
    "class_id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "class_num" integer not null,
    "created_at" timestamp with time zone default now()
);

-- PROFILES table (replaces USERS table)
create table "public"."PROFILES" (
    "id" uuid not null,
    "class_id" bigint,
    "name" character varying(50),
    "profile_image_uri" text,
    "created_at" timestamp with time zone default now()
);

-- MEMORIES table (unchanged)
create table "public"."MEMORIES" (
    "memory_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "name" character varying(255),
    "image_uri" text,
    "created_at" timestamp with time zone default now()
);

-- POLLS table (updated to reference PROFILES)
create table "public"."POLLS" (
    "poll_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "made_by" uuid not null,
    "poll_name" character varying(255) not null,
    "created_at" timestamp with time zone default now(),
    "deadline" timestamp with time zone
);

-- POLL_OPTIONS table (unchanged)
create table "public"."POLL_OPTIONS" (
    "option_id" bigint generated by default as identity not null,
    "poll_id" bigint not null,
    "option_name" character varying(255) not null
);

-- PROJECTS table (updated to reference PROFILES)
create table "public"."PROJECTS" (
    "project_id" bigint generated by default as identity not null,
    "project_name" character varying(100) not null,
    "class_id" bigint not null,
    "week_num" integer,
    "profile_id_1" uuid not null,
    "profile_id_2" uuid not null,
    "created_at" timestamp with time zone default now(),
    "planning" text,
    "progress" integer default 0
);

-- SCHEDULES table (unchanged)
create table "public"."SCHEDULES" (
    "schedule_id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "related_poll" bigint,
    "schedule_name" character varying(255) not null,
    "description" text,
    "when" timestamp with time zone not null,
    "created_at" timestamp with time zone default now()
);

-- SCHEDULE_USERS table (updated to reference PROFILES)
create table "public"."SCHEDULE_USERS" (
    "schedule_id" bigint not null,
    "profile_id" uuid not null,
    "role" character varying(50),
    "status" character varying(20)
);

-- SCRUMS table (unchanged)
create table "public"."SCRUMS" (
    "scrum_id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "date" date not null,
    "done" text,
    "plan" text,
    "others" text
);

-- TOPICS table (updated to reference PROFILES)
create table "public"."TOPICS" (
    "topic_id" bigint generated by default as identity not null,
    "creator_id" uuid not null,
    "title" character varying(255) not null,
    "description" text,
    "created_at" timestamp with time zone default now()
);

-- TOPIC_INTERESTS table (updated to reference PROFILES)
create table "public"."TOPIC_INTERESTS" (
    "profile_id" uuid not null,
    "topic_id" bigint not null,
    "level" integer,
    "expressed_at" timestamp with time zone default now()
);

-- VOTES table (updated to reference PROFILES)
create table "public"."VOTES" (
    "vote_id" bigint generated by default as identity not null,
    "profile_id" uuid not null,
    "poll_id" bigint not null,
    "option_id" bigint not null,
    "voted_at" timestamp with time zone default now()
);

-- Create unique indexes
CREATE UNIQUE INDEX "SEASONS_pkey" ON public."SEASONS" USING btree (season_id);
CREATE UNIQUE INDEX "CAMP_CLASSES_pkey" ON public."CAMP_CLASSES" USING btree (class_id);
CREATE UNIQUE INDEX "PROFILES_pkey" ON public."PROFILES" USING btree (id);
CREATE UNIQUE INDEX "MEMORIES_pkey" ON public."MEMORIES" USING btree (memory_id);
CREATE UNIQUE INDEX "POLLS_pkey" ON public."POLLS" USING btree (poll_id);
CREATE UNIQUE INDEX "POLL_OPTIONS_pkey" ON public."POLL_OPTIONS" USING btree (option_id);
CREATE UNIQUE INDEX "PROJECTS_pkey" ON public."PROJECTS" USING btree (project_id);
CREATE UNIQUE INDEX "SCHEDULES_pkey" ON public."SCHEDULES" USING btree (schedule_id);
CREATE UNIQUE INDEX "SCHEDULE_USERS_pkey" ON public."SCHEDULE_USERS" USING btree (schedule_id, profile_id);
CREATE UNIQUE INDEX "SCRUMS_pkey" ON public."SCRUMS" USING btree (scrum_id);
CREATE UNIQUE INDEX "TOPICS_pkey" ON public."TOPICS" USING btree (topic_id);
CREATE UNIQUE INDEX "TOPIC_INTERESTS_pkey" ON public."TOPIC_INTERESTS" USING btree (profile_id, topic_id);
CREATE UNIQUE INDEX "VOTES_pkey" ON public."VOTES" USING btree (vote_id);
CREATE UNIQUE INDEX "VOTES_profile_id_poll_id_key" ON public."VOTES" USING btree (profile_id, poll_id);

-- Add primary key constraints
alter table "public"."SEASONS" add constraint "SEASONS_pkey" PRIMARY KEY using index "SEASONS_pkey";
alter table "public"."CAMP_CLASSES" add constraint "CAMP_CLASSES_pkey" PRIMARY KEY using index "CAMP_CLASSES_pkey";
alter table "public"."PROFILES" add constraint "PROFILES_pkey" PRIMARY KEY using index "PROFILES_pkey";
alter table "public"."MEMORIES" add constraint "MEMORIES_pkey" PRIMARY KEY using index "MEMORIES_pkey";
alter table "public"."POLLS" add constraint "POLLS_pkey" PRIMARY KEY using index "POLLS_pkey";
alter table "public"."POLL_OPTIONS" add constraint "POLL_OPTIONS_pkey" PRIMARY KEY using index "POLL_OPTIONS_pkey";
alter table "public"."PROJECTS" add constraint "PROJECTS_pkey" PRIMARY KEY using index "PROJECTS_pkey";
alter table "public"."SCHEDULES" add constraint "SCHEDULES_pkey" PRIMARY KEY using index "SCHEDULES_pkey";
alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_pkey" PRIMARY KEY using index "SCHEDULE_USERS_pkey";
alter table "public"."SCRUMS" add constraint "SCRUMS_pkey" PRIMARY KEY using index "SCRUMS_pkey";
alter table "public"."TOPICS" add constraint "TOPICS_pkey" PRIMARY KEY using index "TOPICS_pkey";
alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_pkey" PRIMARY KEY using index "TOPIC_INTERESTS_pkey";
alter table "public"."VOTES" add constraint "VOTES_pkey" PRIMARY KEY using index "VOTES_pkey";

-- Add foreign key constraints
alter table "public"."CAMP_CLASSES" add constraint "CAMP_CLASSES_season_id_fkey" FOREIGN KEY (season_id) REFERENCES "SEASONS"(season_id) not valid;
alter table "public"."CAMP_CLASSES" validate constraint "CAMP_CLASSES_season_id_fkey";

alter table "public"."PROFILES" add constraint "PROFILES_id_fkey" FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE not valid;
alter table "public"."PROFILES" validate constraint "PROFILES_id_fkey";

alter table "public"."PROFILES" add constraint "PROFILES_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;
alter table "public"."PROFILES" validate constraint "PROFILES_class_id_fkey";

alter table "public"."MEMORIES" add constraint "MEMORIES_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;
alter table "public"."MEMORIES" validate constraint "MEMORIES_class_id_fkey";

alter table "public"."POLLS" add constraint "POLLS_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;
alter table "public"."POLLS" validate constraint "POLLS_class_id_fkey";

alter table "public"."POLLS" add constraint "POLLS_made_by_fkey" FOREIGN KEY (made_by) REFERENCES "PROFILES"(id) not valid;
alter table "public"."POLLS" validate constraint "POLLS_made_by_fkey";

alter table "public"."POLL_OPTIONS" add constraint "POLL_OPTIONS_poll_id_fkey" FOREIGN KEY (poll_id) REFERENCES "POLLS"(poll_id) ON DELETE CASCADE not valid;
alter table "public"."POLL_OPTIONS" validate constraint "POLL_OPTIONS_poll_id_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;
alter table "public"."PROJECTS" validate constraint "PROJECTS_class_id_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_profile_id_1_fkey" FOREIGN KEY (profile_id_1) REFERENCES "PROFILES"(id) not valid;
alter table "public"."PROJECTS" validate constraint "PROJECTS_profile_id_1_fkey";

alter table "public"."PROJECTS" add constraint "PROJECTS_profile_id_2_fkey" FOREIGN KEY (profile_id_2) REFERENCES "PROFILES"(id) not valid;
alter table "public"."PROJECTS" validate constraint "PROJECTS_profile_id_2_fkey";

alter table "public"."SCHEDULES" add constraint "SCHEDULES_class_id_fkey" FOREIGN KEY (class_id) REFERENCES "CAMP_CLASSES"(class_id) not valid;
alter table "public"."SCHEDULES" validate constraint "SCHEDULES_class_id_fkey";

alter table "public"."SCHEDULES" add constraint "SCHEDULES_related_poll_fkey" FOREIGN KEY (related_poll) REFERENCES "POLLS"(poll_id) ON DELETE SET NULL not valid;
alter table "public"."SCHEDULES" validate constraint "SCHEDULES_related_poll_fkey";

alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_schedule_id_fkey" FOREIGN KEY (schedule_id) REFERENCES "SCHEDULES"(schedule_id) ON DELETE CASCADE not valid;
alter table "public"."SCHEDULE_USERS" validate constraint "SCHEDULE_USERS_schedule_id_fkey";

alter table "public"."SCHEDULE_USERS" add constraint "SCHEDULE_USERS_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES "PROFILES"(id) ON DELETE CASCADE not valid;
alter table "public"."SCHEDULE_USERS" validate constraint "SCHEDULE_USERS_profile_id_fkey";

alter table "public"."SCRUMS" add constraint "SCRUMS_project_id_fkey" FOREIGN KEY (project_id) REFERENCES "PROJECTS"(project_id) ON DELETE CASCADE not valid;
alter table "public"."SCRUMS" validate constraint "SCRUMS_project_id_fkey";

alter table "public"."TOPICS" add constraint "TOPICS_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES "PROFILES"(id) not valid;
alter table "public"."TOPICS" validate constraint "TOPICS_creator_id_fkey";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_level_check" CHECK (((level >= 1) AND (level <= 5))) not valid;
alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_level_check";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES "TOPICS"(topic_id) ON DELETE CASCADE not valid;
alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_topic_id_fkey";

alter table "public"."TOPIC_INTERESTS" add constraint "TOPIC_INTERESTS_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES "PROFILES"(id) ON DELETE CASCADE not valid;
alter table "public"."TOPIC_INTERESTS" validate constraint "TOPIC_INTERESTS_profile_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_option_id_fkey" FOREIGN KEY (option_id) REFERENCES "POLL_OPTIONS"(option_id) ON DELETE CASCADE not valid;
alter table "public"."VOTES" validate constraint "VOTES_option_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_poll_id_fkey" FOREIGN KEY (poll_id) REFERENCES "POLLS"(poll_id) ON DELETE CASCADE not valid;
alter table "public"."VOTES" validate constraint "VOTES_poll_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES "PROFILES"(id) ON DELETE CASCADE not valid;
alter table "public"."VOTES" validate constraint "VOTES_profile_id_fkey";

alter table "public"."VOTES" add constraint "VOTES_profile_id_poll_id_key" UNIQUE using index "VOTES_profile_id_poll_id_key";

-- Grant permissions for all tables
-- SEASONS
grant delete on table "public"."SEASONS" to "anon";
grant insert on table "public"."SEASONS" to "anon";
grant references on table "public"."SEASONS" to "anon";
grant select on table "public"."SEASONS" to "anon";
grant trigger on table "public"."SEASONS" to "anon";
grant truncate on table "public"."SEASONS" to "anon";
grant update on table "public"."SEASONS" to "anon";
grant delete on table "public"."SEASONS" to "authenticated";
grant insert on table "public"."SEASONS" to "authenticated";
grant references on table "public"."SEASONS" to "authenticated";
grant select on table "public"."SEASONS" to "authenticated";
grant trigger on table "public"."SEASONS" to "authenticated";
grant truncate on table "public"."SEASONS" to "authenticated";
grant update on table "public"."SEASONS" to "authenticated";
grant delete on table "public"."SEASONS" to "service_role";
grant insert on table "public"."SEASONS" to "service_role";
grant references on table "public"."SEASONS" to "service_role";
grant select on table "public"."SEASONS" to "service_role";
grant trigger on table "public"."SEASONS" to "service_role";
grant truncate on table "public"."SEASONS" to "service_role";
grant update on table "public"."SEASONS" to "service_role";

-- CAMP_CLASSES
grant delete on table "public"."CAMP_CLASSES" to "anon";
grant insert on table "public"."CAMP_CLASSES" to "anon";
grant references on table "public"."CAMP_CLASSES" to "anon";
grant select on table "public"."CAMP_CLASSES" to "anon";
grant trigger on table "public"."CAMP_CLASSES" to "anon";
grant truncate on table "public"."CAMP_CLASSES" to "anon";
grant update on table "public"."CAMP_CLASSES" to "anon";
grant delete on table "public"."CAMP_CLASSES" to "authenticated";
grant insert on table "public"."CAMP_CLASSES" to "authenticated";
grant references on table "public"."CAMP_CLASSES" to "authenticated";
grant select on table "public"."CAMP_CLASSES" to "authenticated";
grant trigger on table "public"."CAMP_CLASSES" to "authenticated";
grant truncate on table "public"."CAMP_CLASSES" to "authenticated";
grant update on table "public"."CAMP_CLASSES" to "authenticated";
grant delete on table "public"."CAMP_CLASSES" to "service_role";
grant insert on table "public"."CAMP_CLASSES" to "service_role";
grant references on table "public"."CAMP_CLASSES" to "service_role";
grant select on table "public"."CAMP_CLASSES" to "service_role";
grant trigger on table "public"."CAMP_CLASSES" to "service_role";
grant truncate on table "public"."CAMP_CLASSES" to "service_role";
grant update on table "public"."CAMP_CLASSES" to "service_role";

-- PROFILES
grant delete on table "public"."PROFILES" to "anon";
grant insert on table "public"."PROFILES" to "anon";
grant references on table "public"."PROFILES" to "anon";
grant select on table "public"."PROFILES" to "anon";
grant trigger on table "public"."PROFILES" to "anon";
grant truncate on table "public"."PROFILES" to "anon";
grant update on table "public"."PROFILES" to "anon";
grant delete on table "public"."PROFILES" to "authenticated";
grant insert on table "public"."PROFILES" to "authenticated";
grant references on table "public"."PROFILES" to "authenticated";
grant select on table "public"."PROFILES" to "authenticated";
grant trigger on table "public"."PROFILES" to "authenticated";
grant truncate on table "public"."PROFILES" to "authenticated";
grant update on table "public"."PROFILES" to "authenticated";
grant delete on table "public"."PROFILES" to "service_role";
grant insert on table "public"."PROFILES" to "service_role";
grant references on table "public"."PROFILES" to "service_role";
grant select on table "public"."PROFILES" to "service_role";
grant trigger on table "public"."PROFILES" to "service_role";
grant truncate on table "public"."PROFILES" to "service_role";
grant update on table "public"."PROFILES" to "service_role";

-- MEMORIES
grant delete on table "public"."MEMORIES" to "anon";
grant insert on table "public"."MEMORIES" to "anon";
grant references on table "public"."MEMORIES" to "anon";
grant select on table "public"."MEMORIES" to "anon";
grant trigger on table "public"."MEMORIES" to "anon";
grant truncate on table "public"."MEMORIES" to "anon";
grant update on table "public"."MEMORIES" to "anon";
grant delete on table "public"."MEMORIES" to "authenticated";
grant insert on table "public"."MEMORIES" to "authenticated";
grant references on table "public"."MEMORIES" to "authenticated";
grant select on table "public"."MEMORIES" to "authenticated";
grant trigger on table "public"."MEMORIES" to "authenticated";
grant truncate on table "public"."MEMORIES" to "authenticated";
grant update on table "public"."MEMORIES" to "authenticated";
grant delete on table "public"."MEMORIES" to "service_role";
grant insert on table "public"."MEMORIES" to "service_role";
grant references on table "public"."MEMORIES" to "service_role";
grant select on table "public"."MEMORIES" to "service_role";
grant trigger on table "public"."MEMORIES" to "service_role";
grant truncate on table "public"."MEMORIES" to "service_role";
grant update on table "public"."MEMORIES" to "service_role";

-- POLLS
grant delete on table "public"."POLLS" to "anon";
grant insert on table "public"."POLLS" to "anon";
grant references on table "public"."POLLS" to "anon";
grant select on table "public"."POLLS" to "anon";
grant trigger on table "public"."POLLS" to "anon";
grant truncate on table "public"."POLLS" to "anon";
grant update on table "public"."POLLS" to "anon";
grant delete on table "public"."POLLS" to "authenticated";
grant insert on table "public"."POLLS" to "authenticated";
grant references on table "public"."POLLS" to "authenticated";
grant select on table "public"."POLLS" to "authenticated";
grant trigger on table "public"."POLLS" to "authenticated";
grant truncate on table "public"."POLLS" to "authenticated";
grant update on table "public"."POLLS" to "authenticated";
grant delete on table "public"."POLLS" to "service_role";
grant insert on table "public"."POLLS" to "service_role";
grant references on table "public"."POLLS" to "service_role";
grant select on table "public"."POLLS" to "service_role";
grant trigger on table "public"."POLLS" to "service_role";
grant truncate on table "public"."POLLS" to "service_role";
grant update on table "public"."POLLS" to "service_role";

-- POLL_OPTIONS
grant delete on table "public"."POLL_OPTIONS" to "anon";
grant insert on table "public"."POLL_OPTIONS" to "anon";
grant references on table "public"."POLL_OPTIONS" to "anon";
grant select on table "public"."POLL_OPTIONS" to "anon";
grant trigger on table "public"."POLL_OPTIONS" to "anon";
grant truncate on table "public"."POLL_OPTIONS" to "anon";
grant update on table "public"."POLL_OPTIONS" to "anon";
grant delete on table "public"."POLL_OPTIONS" to "authenticated";
grant insert on table "public"."POLL_OPTIONS" to "authenticated";
grant references on table "public"."POLL_OPTIONS" to "authenticated";
grant select on table "public"."POLL_OPTIONS" to "authenticated";
grant trigger on table "public"."POLL_OPTIONS" to "authenticated";
grant truncate on table "public"."POLL_OPTIONS" to "authenticated";
grant update on table "public"."POLL_OPTIONS" to "authenticated";
grant delete on table "public"."POLL_OPTIONS" to "service_role";
grant insert on table "public"."POLL_OPTIONS" to "service_role";
grant references on table "public"."POLL_OPTIONS" to "service_role";
grant select on table "public"."POLL_OPTIONS" to "service_role";
grant trigger on table "public"."POLL_OPTIONS" to "service_role";
grant truncate on table "public"."POLL_OPTIONS" to "service_role";
grant update on table "public"."POLL_OPTIONS" to "service_role";

-- PROJECTS
grant delete on table "public"."PROJECTS" to "anon";
grant insert on table "public"."PROJECTS" to "anon";
grant references on table "public"."PROJECTS" to "anon";
grant select on table "public"."PROJECTS" to "anon";
grant trigger on table "public"."PROJECTS" to "anon";
grant truncate on table "public"."PROJECTS" to "anon";
grant update on table "public"."PROJECTS" to "anon";
grant delete on table "public"."PROJECTS" to "authenticated";
grant insert on table "public"."PROJECTS" to "authenticated";
grant references on table "public"."PROJECTS" to "authenticated";
grant select on table "public"."PROJECTS" to "authenticated";
grant trigger on table "public"."PROJECTS" to "authenticated";
grant truncate on table "public"."PROJECTS" to "authenticated";
grant update on table "public"."PROJECTS" to "authenticated";
grant delete on table "public"."PROJECTS" to "service_role";
grant insert on table "public"."PROJECTS" to "service_role";
grant references on table "public"."PROJECTS" to "service_role";
grant select on table "public"."PROJECTS" to "service_role";
grant trigger on table "public"."PROJECTS" to "service_role";
grant truncate on table "public"."PROJECTS" to "service_role";
grant update on table "public"."PROJECTS" to "service_role";

-- SCHEDULES
grant delete on table "public"."SCHEDULES" to "anon";
grant insert on table "public"."SCHEDULES" to "anon";
grant references on table "public"."SCHEDULES" to "anon";
grant select on table "public"."SCHEDULES" to "anon";
grant trigger on table "public"."SCHEDULES" to "anon";
grant truncate on table "public"."SCHEDULES" to "anon";
grant update on table "public"."SCHEDULES" to "anon";
grant delete on table "public"."SCHEDULES" to "authenticated";
grant insert on table "public"."SCHEDULES" to "authenticated";
grant references on table "public"."SCHEDULES" to "authenticated";
grant select on table "public"."SCHEDULES" to "authenticated";
grant trigger on table "public"."SCHEDULES" to "authenticated";
grant truncate on table "public"."SCHEDULES" to "authenticated";
grant update on table "public"."SCHEDULES" to "authenticated";
grant delete on table "public"."SCHEDULES" to "service_role";
grant insert on table "public"."SCHEDULES" to "service_role";
grant references on table "public"."SCHEDULES" to "service_role";
grant select on table "public"."SCHEDULES" to "service_role";
grant trigger on table "public"."SCHEDULES" to "service_role";
grant truncate on table "public"."SCHEDULES" to "service_role";
grant update on table "public"."SCHEDULES" to "service_role";

-- SCHEDULE_USERS
grant delete on table "public"."SCHEDULE_USERS" to "anon";
grant insert on table "public"."SCHEDULE_USERS" to "anon";
grant references on table "public"."SCHEDULE_USERS" to "anon";
grant select on table "public"."SCHEDULE_USERS" to "anon";
grant trigger on table "public"."SCHEDULE_USERS" to "anon";
grant truncate on table "public"."SCHEDULE_USERS" to "anon";
grant update on table "public"."SCHEDULE_USERS" to "anon";
grant delete on table "public"."SCHEDULE_USERS" to "authenticated";
grant insert on table "public"."SCHEDULE_USERS" to "authenticated";
grant references on table "public"."SCHEDULE_USERS" to "authenticated";
grant select on table "public"."SCHEDULE_USERS" to "authenticated";
grant trigger on table "public"."SCHEDULE_USERS" to "authenticated";
grant truncate on table "public"."SCHEDULE_USERS" to "authenticated";
grant update on table "public"."SCHEDULE_USERS" to "authenticated";
grant delete on table "public"."SCHEDULE_USERS" to "service_role";
grant insert on table "public"."SCHEDULE_USERS" to "service_role";
grant references on table "public"."SCHEDULE_USERS" to "service_role";
grant select on table "public"."SCHEDULE_USERS" to "service_role";
grant trigger on table "public"."SCHEDULE_USERS" to "service_role";
grant truncate on table "public"."SCHEDULE_USERS" to "service_role";
grant update on table "public"."SCHEDULE_USERS" to "service_role";

-- SCRUMS
grant delete on table "public"."SCRUMS" to "anon";
grant insert on table "public"."SCRUMS" to "anon";
grant references on table "public"."SCRUMS" to "anon";
grant select on table "public"."SCRUMS" to "anon";
grant trigger on table "public"."SCRUMS" to "anon";
grant truncate on table "public"."SCRUMS" to "anon";
grant update on table "public"."SCRUMS" to "anon";
grant delete on table "public"."SCRUMS" to "authenticated";
grant insert on table "public"."SCRUMS" to "authenticated";
grant references on table "public"."SCRUMS" to "authenticated";
grant select on table "public"."SCRUMS" to "authenticated";
grant trigger on table "public"."SCRUMS" to "authenticated";
grant truncate on table "public"."SCRUMS" to "authenticated";
grant update on table "public"."SCRUMS" to "authenticated";
grant delete on table "public"."SCRUMS" to "service_role";
grant insert on table "public"."SCRUMS" to "service_role";
grant references on table "public"."SCRUMS" to "service_role";
grant select on table "public"."SCRUMS" to "service_role";
grant trigger on table "public"."SCRUMS" to "service_role";
grant truncate on table "public"."SCRUMS" to "service_role";
grant update on table "public"."SCRUMS" to "service_role";

-- TOPICS
grant delete on table "public"."TOPICS" to "anon";
grant insert on table "public"."TOPICS" to "anon";
grant references on table "public"."TOPICS" to "anon";
grant select on table "public"."TOPICS" to "anon";
grant trigger on table "public"."TOPICS" to "anon";
grant truncate on table "public"."TOPICS" to "anon";
grant update on table "public"."TOPICS" to "anon";
grant delete on table "public"."TOPICS" to "authenticated";
grant insert on table "public"."TOPICS" to "authenticated";
grant references on table "public"."TOPICS" to "authenticated";
grant select on table "public"."TOPICS" to "authenticated";
grant trigger on table "public"."TOPICS" to "authenticated";
grant truncate on table "public"."TOPICS" to "authenticated";
grant update on table "public"."TOPICS" to "authenticated";
grant delete on table "public"."TOPICS" to "service_role";
grant insert on table "public"."TOPICS" to "service_role";
grant references on table "public"."TOPICS" to "service_role";
grant select on table "public"."TOPICS" to "service_role";
grant trigger on table "public"."TOPICS" to "service_role";
grant truncate on table "public"."TOPICS" to "service_role";
grant update on table "public"."TOPICS" to "service_role";

-- TOPIC_INTERESTS
grant delete on table "public"."TOPIC_INTERESTS" to "anon";
grant insert on table "public"."TOPIC_INTERESTS" to "anon";
grant references on table "public"."TOPIC_INTERESTS" to "anon";
grant select on table "public"."TOPIC_INTERESTS" to "anon";
grant trigger on table "public"."TOPIC_INTERESTS" to "anon";
grant truncate on table "public"."TOPIC_INTERESTS" to "anon";
grant update on table "public"."TOPIC_INTERESTS" to "anon";
grant delete on table "public"."TOPIC_INTERESTS" to "authenticated";
grant insert on table "public"."TOPIC_INTERESTS" to "authenticated";
grant references on table "public"."TOPIC_INTERESTS" to "authenticated";
grant select on table "public"."TOPIC_INTERESTS" to "authenticated";
grant trigger on table "public"."TOPIC_INTERESTS" to "authenticated";
grant truncate on table "public"."TOPIC_INTERESTS" to "authenticated";
grant update on table "public"."TOPIC_INTERESTS" to "authenticated";
grant delete on table "public"."TOPIC_INTERESTS" to "service_role";
grant insert on table "public"."TOPIC_INTERESTS" to "service_role";
grant references on table "public"."TOPIC_INTERESTS" to "service_role";
grant select on table "public"."TOPIC_INTERESTS" to "service_role";
grant trigger on table "public"."TOPIC_INTERESTS" to "service_role";
grant truncate on table "public"."TOPIC_INTERESTS" to "service_role";
grant update on table "public"."TOPIC_INTERESTS" to "service_role";

-- VOTES
grant delete on table "public"."VOTES" to "anon";
grant insert on table "public"."VOTES" to "anon";
grant references on table "public"."VOTES" to "anon";
grant select on table "public"."VOTES" to "anon";
grant trigger on table "public"."VOTES" to "anon";
grant truncate on table "public"."VOTES" to "anon";
grant update on table "public"."VOTES" to "anon";
grant delete on table "public"."VOTES" to "authenticated";
grant insert on table "public"."VOTES" to "authenticated";
grant references on table "public"."VOTES" to "authenticated";
grant select on table "public"."VOTES" to "authenticated";
grant trigger on table "public"."VOTES" to "authenticated";
grant truncate on table "public"."VOTES" to "authenticated";
grant update on table "public"."VOTES" to "authenticated";
grant delete on table "public"."VOTES" to "service_role";
grant insert on table "public"."VOTES" to "service_role";
grant references on table "public"."VOTES" to "service_role";
grant select on table "public"."VOTES" to "service_role";
grant trigger on table "public"."VOTES" to "service_role";
grant truncate on table "public"."VOTES" to "service_role";
grant update on table "public"."VOTES" to "service_role";

-- Create trigger function to handle new user registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public."PROFILES" (id, name)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'name');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

-- Create trigger to automatically create profile when new user signs up
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Add table comments
COMMENT ON TABLE public."PROFILES" IS 'Stores public profile information for each user, linked to auth.users';
COMMENT ON TABLE public."SEASONS" IS 'Different camp seasons (e.g., Summer 2024, Winter 2024)';
COMMENT ON TABLE public."CAMP_CLASSES" IS 'Classes within each season';
COMMENT ON TABLE public."MEMORIES" IS 'Shared memories/photos for each class';
COMMENT ON TABLE public."POLLS" IS 'Polls created by users';
COMMENT ON TABLE public."POLL_OPTIONS" IS 'Options for each poll';
COMMENT ON TABLE public."PROJECTS" IS 'Team projects between two users';
COMMENT ON TABLE public."SCHEDULES" IS 'Scheduled events for classes';
COMMENT ON TABLE public."SCHEDULE_USERS" IS 'User participation in scheduled events';
COMMENT ON TABLE public."SCRUMS" IS 'Daily scrum entries for projects';
COMMENT ON TABLE public."TOPICS" IS 'Discussion topics created by users';
COMMENT ON TABLE public."TOPIC_INTERESTS" IS 'User interest levels in topics';
COMMENT ON TABLE public."VOTES" IS 'User votes on poll options'; 